dbus-send: Fix compiler warning for char array initialization
```
/builds/dbus/dbus/tools/dbus-send.c:149:23: error: initializer-string
for array of 'char' truncates NUL terminator but destination lacks
'nonstring' attribute (3 chars into 2 available)
[-Werror=unterminated-string-initialization]
  149 |         char sig[2] = "\0\0";
```

The initializer could be changed to `"\0"`, but writing it out as an
array seems clearer.

Signed-off-by: Simon McVittie <smcv@collabora.com>